#!/usr/bin/env python3
"""Baseline experiment -- IMMUTABLE reference point.

XGBoost on all stocks and all features. Reference score for comparison.
Do NOT edit this file.
"""

import sys
from pathlib import Path

from xgboost import XGBClassifier

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lib.data import LABEL_COL, list_features, load_dataset, scale, temporal_split
from lib.eval import tiered_eval

DATASET_PATH = "data/datasets/20260115/dataset.parquet"


def run():
    features = list_features(None)
    df, feature_cols = load_dataset(DATASET_PATH, features=features)

    train, val, test = temporal_split(df)
    train_s, val_s, test_s, scaler = scale(train, val, test, feature_cols)

    X_train = train_s[feature_cols].values
    y_train = train_s[LABEL_COL].values
    X_val = val_s[feature_cols].values
    y_val = val_s[LABEL_COL].values

    neg = (y_train == 0).sum()
    pos = (y_train == 1).sum()

    model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=neg / pos,
        tree_method="hist",
        random_state=42,
        n_jobs=-1,
        verbosity=0,
    )
    model.fit(X_train, y_train)

    y_pred_proba = model.predict_proba(X_val)[:, 1]

    results = tiered_eval(val, y_val, y_pred_proba)
    score = results.get("tier3", float("-inf"))
    print(f"\nBASELINE COMPOSITE_SCORE={score:.4f}")
    return results


if __name__ == "__main__":
    run()
