#!/usr/bin/env python3
"""Baseline experiment -- IMMUTABLE reference point.

Simple logistic regression on base features. Establishes the minimum
the researcher must beat. Do NOT edit this file.
"""

import sys
from pathlib import Path

from sklearn.linear_model import LogisticRegression

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lib.data import LABEL_COL, list_features, load_dataset, scale, temporal_split
from lib.eval import tiered_eval

DATASET_PATH = "data/datasets/20260115/dataset.parquet"
STOCKS = ["AAPL", "MSFT", "GOOG", "AMZN", "TSLA"]


def run():
    features = list_features("base")
    df, feature_cols = load_dataset(DATASET_PATH, stocks=STOCKS, features=features)

    train, val, test = temporal_split(df)
    train_s, val_s, test_s, scaler = scale(train, val, test, feature_cols)

    X_train = train_s[feature_cols].values
    y_train = train_s[LABEL_COL].values
    X_val = val_s[feature_cols].values
    y_val = val_s[LABEL_COL].values

    neg = (y_train == 0).sum()
    pos = (y_train == 1).sum()

    model = LogisticRegression(
        class_weight={0: 1, 1: neg / pos},
        max_iter=1000,
        random_state=42,
    )
    model.fit(X_train, y_train)

    y_pred_proba = model.predict_proba(X_val)[:, 1]
    y_pred = (y_pred_proba > 0.5).astype(int)
    print(f"Predictions: {y_pred.sum()} signals / {len(y_pred)} total")

    results = tiered_eval(val, y_val, y_pred, y_pred_proba)
    score = results.get("tier3", float("-inf"))
    print(f"\nBASELINE COMPOSITE_SCORE={score:.4f}")
    return results


if __name__ == "__main__":
    run()
